# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/osx'
require 'joybox'

Motion::Project::App.setup do |app|
  app.name = 'Hello World'
  app.icon = 'icon.icns'
end
