# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require

Motion::Project::App.setup do |app|
  
  app.name = 'Gorillas'
  app.identifier = 'gorillas.joybox.io'
  app.interface_orientations = [:landscape_left]
end
