# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'joybox'

Motion::Project::App.setup do |app|
  app.name = 'Physics'
  app.icons = ['icon.png', 'icon@2x.png']
  app.prerendered_icon = true
end
